### ISSUE TITLE
🛑 American Fence and Deck is down

### ISSUE THREAD

**Issue by pearanalytics** [pearanalytics/uptime#337]
In [`ab7c7b4`](https://github.com/pearanalytics/uptime/commit/ab7c7b4d38a1451e66bbe670480f95ad493b27a0
), American Fence and Deck (https://americanfencedeck.com) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by vidluther** [comment]
migrating back to pressable. just a glitch in the dns matrix.
